### ISSUE TITLE
Location of xboost lib

### ISSUE THREAD

**Issue by hackhowtofaq** [ankane/xgb#2]
I cloned & build from xboost repo.  Now, I have `libxgboost.so` inside the cloned dir.

Where do I have to put `libxgboost.so` so this gem can find it?

Ty.

**Comment by ankane** [comment]
Hey @hackhowtofaq, try `/usr/local/lib`. You can also do:

```ruby
Xgb.ffi_lib << "/path/to/libxgboost.so"
```

**Comment by hackhowtofaq** [comment]
That was what I was looking! Thank you a lot!
